#preload = /home/garciasa/Wallpaper-Bank/wallpapers/Wall.png
#wallpaper = , /home/garciasa/Wallpaper-Bank/wallpapers/Wall.png
wallpaper {
    monitor = DP-4
    path = /home/garciasa/Wallpaper-Bank/wallpapers/Wall.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/garciasa/Wallpaper-Bank/wallpapers/Wall.png
    fit_mode = cover
}
